#!/usr/bin/env python3
"""Generate Lua font-metrics tables from the DejaVu fonts.

Used only by the headless test renderer so that Lua-side text measurement and
the Pillow-side rasterisation agree pixel for pixel.
"""
import os
from PIL import ImageFont

FONTS = {
    "regular": "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf",
    "bold": "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf",
    "mono": "/usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf",
}
SIZE = 100
OUT = os.path.join(os.path.dirname(__file__), "..", "tests", "metrics_dejavu.lua")

lines = ["-- generated by tools/gen_metrics.py -- do not edit", "return {"]
for name, path in FONTS.items():
    font = ImageFont.truetype(path, SIZE)
    lines.append("  %s = {" % name)
    entries = []
    for code in range(32, 127):
        ch = chr(code)
        adv = font.getlength(ch)
        entries.append("[%d]=%.5f" % (code, adv / SIZE))
    # Cyrillic block, so the demo menus in Russian measure correctly too
    for code in range(0x400, 0x460):
        ch = chr(code)
        adv = font.getlength(ch)
        entries.append("[%d]=%.5f" % (code, adv / SIZE))
    for i in range(0, len(entries), 6):
        lines.append("    " + ", ".join(entries[i:i + 6]) + ",")
    lines.append("  },")
lines.append("}")

with open(os.path.abspath(OUT), "w") as f:
    f.write("\n".join(lines) + "\n")
print("wrote", os.path.abspath(OUT))
